---
name: Lint

on:
  workflow_call:
    inputs:
      working_dir:
        type: string
        required: false
        default: ${{ github.workspace }}
      php_version:
        description: PHP version with which the scripts are executed
        default: "8.4"
        required: false
        type: string

jobs:
  phpstan:
    name: PHPStan (PHP ${{ inputs.php_version }})
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_dir }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: kilip/gh-common/actions/setup-php
        with:
          php_version: ${{ inputs.php_version }}

      - name: Cache PHPStan results
        uses: actions/cache@v4
        with:
          path: /tmp/phpstan
          key: phpstan-php${{ inputs.php_version }}-${{ github.sha }}
          restore-keys: |
            phpstan-php${{ inputs.php_version }}-
            phpstan-
        continue-on-error: true

      - name: Run PHPStan analysis
        run: |
          ./vendor/bin/phpstan --version
          ./vendor/bin/phpstan analyse --no-interaction --no-progress --ansi
