---
on:
  workflow_call:
    inputs:
      working_dir:
        type: string
        required: true
      php_version:
        description: PHP version with which the scripts are executed
        required: true
        type: string

jobs:
  phpstan:
    name: PHPStan (PHP ${{ inputs.php_version }})
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: kilip/gh-common/.github/actions/setup-php@main
        with:
          php_version: ${{ inputs.php_version }}
          working_dir: ${{ inputs.working_dir }}

      - name: Cache PHPStan results
        uses: actions/cache@v4
        with:
          path: /tmp/phpstan
          key: phpstan-php${{ inputs.php_version }}-${{ github.sha }}
          restore-keys: |
            phpstan-php${{ inputs.php_version }}-
            phpstan-
        continue-on-error: true

      - name: Run PHPStan analysis
        run: |
          ./vendor/bin/phpstan --version
          ./vendor/bin/phpstan analyse --no-interaction --no-progress --ansi
