---
name: Release

on:
  workflow_call:
    inputs:
      release_branches:
        type: string
        required: false
        default: main

jobs:
  bump-version:
    name: Bump Version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Bump Version
        uses: ./.github/actions/bump-version
        with:
          release_branches: "${{ inputs.release_branches }}"
